$makeindex  = 'makeindex -s gind.ist %O -o %D %S';  # https://tex.stackexchange.com/questions/84870/index-completely-messed-up-in-dtx-file/84872#84872
$pdf_mode = 4;   # from https://tex.stackexchange.com/questions/501492/how-do-i-set-xelatex-as-my-default-engine
$pdf_previewer = 'zathura %S';  # https://tex.stackexchange.com/questions/634529/is-it-possible-to-specify-the-pdf-viewer-in-latexmk-build-command
